### ISSUE TITLE
build error on ubuntu 20.04 and gcc-10

### ISSUE THREAD

**Issue by ZTJiu** [howardlau1999/rdmapp#9]
ubuntu 20.04
gcc-10

rdmapp/src/socket/tcp_connection.cc:108:11: error: ‘::write’ has not been declared; did you mean ‘write_’?
  108 |     n = ::write(channel_->fd(), buffer_, length_);
      |           ^~~~~

Is this ::write a system call or libibverbs-dev interface ?

**Comment by howardlau1999** [comment]
> ubuntu 20.04 gcc-10
> 
> rdmapp/src/socket/tcp_connection.cc:108:11: error: ‘::write’ has not been declared; did you mean ‘write_’? 108 | n = ::write(channel_->fd(), buffer_, length_); | ^~~~~
> 
> Is this ::write a system call or libibverbs-dev interface ?

It is a Linux system call

**Comment by howardlau1999** [comment]
I can build on Ubuntu 22.04 with gcc 11.2

**Comment by howardlau1999** [comment]
I have added `#include <unistd.h>` in that file, can you check if the latest code compiles? It can compile now on Github Actions.

**Comment by ZTJiu** [comment]
> 

It works. But there's another error 

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '20;REQUIRED'

I fix by change set(CMAKE_CXX_STANDARD 20 REQUIRED) to set(CMAKE_CXX_STANDARD 20) 

Thank you for your reply.
